### ISSUE TITLE
Directory is returned as File when listContents with deep is used.

### ISSUE THREAD

**Issue by cd-champion-dev** [Azure-OSS/azure-storage-php-adapter-flysystem#11]
### Summary

When doing a deep list of a container's contents directories are not properly marked as directories. This does not happen with deep = false.

### Versions

|                                               | Version                  |
|:----------------------------------------------|:-------------------------|
| PHP version                                   | 8.2.25                    |
| Service                                       | blob |
| `azure-storage-php-adapter-flysystem` version | 1.2.0                   |

### Self-enclosed code snippet for reproduction
In your blob container have a directory with a single file in it.

```php
<?php

require_once __DIR__.'/vendor/autoload.php';

use AzureOss\FlysystemAzureBlobStorage\AzureBlobStorageAdapter;
use AzureOss\Storage\Blob\BlobServiceClient;
use League\Flysystem\Filesystem;

$blobServiceClient = BlobServiceClient::fromConnectionString('');
$containerClient = $blobServiceClient->getContainerClient('');
$adapter = new AzureBlobStorageAdapter($containerClient);

$fs = new Filesystem($adapter);

$contents = $fs->listContents('/', true);
foreach ($contents as $entry) {
    if ($entry->isDir()) {
        continue;
    }

    $fs->delete($entry->path());
}
```

### Expected output
The script should successfully complete without errors or output

### Actual output

```txt
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `DELETE <redacted connection string> resulted in a `409 This operation is not permitted on a non-empty directory.` response in /app/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111

Next AzureOss\Storage\Blob\Exceptions\BlobStorageException: This operation is not permitted on a non-empty directory.
RequestId:<redacted>
Time:2024-11-19T21:38:56.6717649Z in /app/vendor/azure-oss/storage/src/Blob/Exceptions/BlobStorageExceptionFactory.php:41
```

**Comment by brecht-vermeersch** [comment]
Hi

Can you give me an example file/folder structure where this happens?
Are you using hierarchical namespaces?

**Comment by d5c4b3** [comment]
I've got a file at `example/test.txt`. 
Unfortunately I only have access to the blob via this API, so I don't know how to answer that question. I dumped `$response->blobs` in case that helps.

```php
array(2) {
  [0]=>
  object(AzureOss\Storage\Blob\Models\Blob)#60 (2) {
    ["name"]=>
    string(7) "example"
    ["properties"]=>
    object(AzureOss\Storage\Blob\Models\BlobProperties)#20 (5) {
      ["lastModified"]=>
      object(DateTimeImmutable)#23 (3) {
        ["date"]=>
        string(26) "2024-10-17 18:19:29.000000"
        ["timezone_type"]=>
        int(2)
        ["timezone"]=>
        string(3) "GMT"
      }
      ["contentLength"]=>
      int(0)
      ["contentType"]=>
      string(0) ""
      ["contentMD5"]=>
      string(0) ""
      ["metadata"]=>
      array(0) {
      }
    }
  }
  [1]=>
  object(AzureOss\Storage\Blob\Models\Blob)#66 (2) {
    ["name"]=>
    string(16) "example/test.txt"
    ["properties"]=>
    object(AzureOss\Storage\Blob\Models\BlobProperties)#11 (5) {
      ["lastModified"]=>
      object(DateTimeImmutable)#57 (3) {
        ["date"]=>
        string(26) "2024-10-17 18:19:29.000000"
        ["timezone_type"]=>
        int(2)
        ["timezone"]=>
        string(3) "GMT"
      }
      ["contentLength"]=>
      int(10)
      ["contentType"]=>
      string(24) "application/octet-stream"
      ["contentMD5"]=>
      string(0) ""
      ["metadata"]=>
      array(0) {
      }
    }
  }
}
```

**Comment by pimjansen** [comment]
I cannot reproduce this at all. When i access the container and list all the stuff in there, folders are not even returned?

**Comment by brecht-vermeersch** [comment]
@pimjansen I can reproduce it. You need a storage account with hierarchical namespace enables. Don't know if we are planning on supporting that...

**Comment by brecht-vermeersch** [comment]
Because we always map a blob to a FileAttributes class. We don't check the resourceType in the response. Now we know that in the case of a hierarchical namespace it can also be a DirectoryAttribute

**Comment by brecht-vermeersch** [comment]
I ran the azure-storage-blob tests on a hierarchical namespace enabled account and 36 tests failed. I don't think it is worth supporting it right now.

@d5c4b3 is there a specific reason why you are not using a normal storage account?

**Comment by d5c4b3** [comment]
I'm writing an integration for a vendor. We were asked to move files into their blob storage, they'd process them and move them to another blob, and we'd pull them down and push them into our system. I don't control the blob storage at all and probably couldn't get them to change it. 

What do you estimate is needed to fix the issue? Is it just check an additional attribute in the response or would it require the adapter needing to know that it's connecting to an account with hierarchical namespaces?

**Comment by brecht-vermeersch** [comment]
Did some research and all official libraries provide this functionality as a separate package

https://www.npmjs.com/package/@azure/storage-file-datalake

https://www.nuget.org/packages/Azure.Storage.Files.DataLake

**Comment by brecht-vermeersch** [comment]
> I'm writing an integration for a vendor. We were asked to move files into their blob storage, they'd process them and move them to another blob, and we'd pull them down and push them into our system. I don't control the blob storage at all and probably couldn't get them to change it. 
> 
> 
> 
> What do you estimate is needed to fix the issue? Is it just check an additional attribute in the response or would it require the adapter needing to know that it's connecting to an account with hierarchical namespaces?

Because they are fundamentally different, I don't think we will ever support it. In the future we can add a separate package just for this type of storage, but at the moment I wont develop it because it will be difficult to maintain something I will ever use

**Comment by pimjansen** [comment]
Agree with above. @brecht-vermeersch is there a way to detect this? Personally i do not like this exception at all so i'd rather check upfront?

**Comment by pimjansen** [comment]
Added a note for this in the docs
